server:
#  ssl:
#    key-store: classpath:myapp.jks
#    key-store-password: Amine123
#    key-password: Amine123
#    key-alias: myapp
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
name:
  value: alibou
spring:
  cloud:
    config:
      override-system-properties: false

management:
  tracing:
    sampling:
      probability: 1.0
